kind: Service
apiVersion: v1
metadata:
  name: weatherdata-v1-0-service
  namespace: weatherdata-testing
  labels:
    app: weatherdata
    version: "1.0"
    environment: testing
spec:
  selector:
    app: weatherdata
    version: "1.0"
    environment: testing
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30110
    port: 9191
    targetPort: 9091